
// Fix: Import React to resolve 'Cannot find namespace React' error when using React.FC or ReactNode
import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'zh' | 'en';

interface TranslationDict {
  [key: string]: string;
}

const translations: Record<Language, TranslationDict> = {
  zh: {
    'nav.dashboard': '仪表盘',
    'nav.manager': '数据管理',
    'nav.export': '导出报告',
    'nav.source': '源码',
    'hero.title': '解锁深度学情洞察',
    'hero.subtitle': '驱动教学决策',
    'hero.desc': '将原始成绩单转化为可落地的教学情报。从管理您的考试数据开始。',
    'hero.cta': '进入数据管理',
    'stat.total_students': '学生总数',
    'stat.classes': '班级总数',
    'stat.above_line': '上线人数',
    'stat.best_score': '最高分',
    'tab.school': '学校概览',
    'tab.comparison': '班级对比',
    'tab.kings': '尖子生对标',
    'tab.parameters': '考试参数',
    'tab.subject': '单科分析',
    'tab.progress': '进退步分析',
    'tab.student': '学生详情',
    'school.config_title': '上线分析参数配置',
    'school.imported_meta': '使用导入元数据推算',
    'school.rank_mode': '按绝对名次',
    'school.percent_mode': '按百分比',
    'school.chart_admissions': '上线情况分析',
    'school.chart_subjects': '学科均分表现',
    'common.subject': '科目',
    'common.class': '班级',
    'common.rank': '名次',
    'common.score': '分数',
    'common.average': '平均分',
    'common.search': '搜索...',
    'common.select_all': '全选',
    'common.participants': '人数',
    'wizard.step': '步骤',
    'wizard.upload': '上传文件',
    'wizard.config': '配置选项',
    'wizard.mapping': '字段映射',
    'wizard.drop_files': '将 Excel 文件拖拽至此处',
    'wizard.supported_formats': '支持格式：.xlsx, .xls',
    'wizard.data_mode': '数据模式',
    'wizard.mode_complete': '全校/级部数据',
    'wizard.mode_complete_desc': '包含完整的年级数据，系统将基于全员计算名次。',
    'wizard.mode_partial': '部分样本/班级',
    'wizard.mode_partial_desc': '仅包含特定群体，计算出的年级排名可能存在偏差。',
    'wizard.table_layout': '表格布局',
    'wizard.layout_multi': '多文件模式 (一考一文)',
    'wizard.layout_multi_desc': '传统格式。选择多个文件来构建学情时间轴。',
    'wizard.layout_single': '单文件多考汇总表',
    'wizard.layout_single_desc': '单个文件内包含多行学生记录（如同一学生占5行）。',
    'wizard.rank_source': '排名判定权威',
    'wizard.source_system': '系统自动计算',
    'wizard.source_system_desc': '系统将基于分数自动推算名次 and 上线情况。',
    'wizard.source_import': '使用导入的元数据',
    'wizard.source_import_desc': '优先使用 Excel 文件中已存在的排名和状态列。',
    'wizard.define_sequence': '定义考试顺序 (英文逗号分隔)',
    'wizard.identity_cols': '身份识别列',
    'wizard.student_name': '学生姓名',
    'wizard.class_group': '所在班级',
    'wizard.choose_col': '-- 选择列 --',
    'wizard.manual_input': '-- 手动输入 --',
    'wizard.enter_class': '输入班级名称 (如：高三1班)',
    'wizard.global_metrics': '全局指标 (可选)',
    'wizard.total_rank_col': '总分排名列',
    'wizard.admission_status': '录取/上线状态',
    'wizard.not_specified': '(未指定)',
    'wizard.subject_mapping': '学科映射',
    'wizard.selected_count': '已选',
    'wizard.mapping_hint': '请先指定“姓名”和“班级”列以解锁学科选择。',
    'wizard.rank_col': '排名列',
    'wizard.btn_discard': '放弃并关闭',
    'wizard.btn_back': '返回',
    'wizard.btn_continue': '继续',
    'wizard.btn_confirm': '确认并生成仪表盘',
    'wizard.processing': '正在处理数据...',
    'wizard.error_no_records': '未找到学生记录，请检查映射。',
    'manager.title': '考试数据管理',
    'manager.desc': '导入、组织并检查您的教学档案。',
    'manager.btn_import': '导入新数据',
    'manager.no_data_title': '暂无导入数据',
    'manager.no_data_desc': '使用导入向导上传 Excel 文件，开启深度的学情分析。',
    'manager.launch_wizard': '启动导入向导',
    'manager.manage_timeline': '管理时间轴',
    'manager.manage_timeline_desc': '通过拖拽左侧手柄调整考试顺序。点击考试项查看详细元数据及校验结果。',
    'manager.timeline_title': '考试时间轴',
    'manager.records': '条记录',
    'manager.full_dataset': '全量数据集',
    'manager.partial_dataset': '部分数据集',
    'manager.delete_confirm': '⚠️ 警告：您即将永久删除与“{name}”相关的所有数据。这包括所有学生的成绩、排名及相关统计。\n\n您确定要继续吗？',
    'manager.details_title': '考试详细元数据',
    'manager.stats_participants': '参测人数',
    'manager.stats_avg': '平均分',
    'manager.stats_cohort_mean': '年级均值',
    'manager.stats_top_perf': '尖子表现',
    'manager.stats_score': '分数',
    'manager.stats_subject_coverage': '学科覆盖',
    'manager.stats_active_classes': '活跃班级',
    'manager.btn_delete_exam': '删除此项考试',
    'manager.select_exam_hint_title': '请选择一项考试',
    'manager.select_exam_hint_desc': '点击时间轴上的任一考试项，即可在此处查看其具体的元数据及分析汇总。',
    'comparison.title': '班级对比分析',
    'comparison.desc': '对比选定群体的学业表现。',
    'comparison.stat_highest_avg': '最高平均分',
    'comparison.stat_points_avg': '分平均分',
    'comparison.stat_most_top10': '最强尖子生 (前{threshold})',
    'comparison.stat_students_top10': '名学生进入前{threshold}',
    'comparison.stat_strongest_bench': '最强基石 (前{threshold})',
    'comparison.stat_students_top50': '名学生进入前{threshold}',
    'comparison.matrix_title': '学科竞争矩阵',
    'comparison.matrix_desc': '突出显示的单元格代表该学科表现领先的班级。',
    'comparison.matrix_header': '科目 / 指标',
    'comparison.matrix_total_avg': '总平均分',
    'comparison.matrix_subject_avg': '单科平均分',
    'comparison.matrix_rank_dist': '名次分布 (顶尖层级)',
    'comparison.count': '人数',
    'comparison.chart_gap': '学科表现差距',
    'comparison.chart_density': '精英密度热力图',
    'comparison.chart_population_dist': '各班顶尖名次人数占比',
    'comparison.ownership_title': '精英占有率分析 (Top {threshold})',
    'comparison.ownership_selector': '对比阈值',
    'comparison.other_classes': '其他班级/未分配',
    'comparison.tier_others': '其他名次',
    'kings.title': '班级尖子生对标',
    'kings.desc': '对比班级领跑者与年级顶尖高手的差距。',
    'kings.selector_prefix': '对比班级',
    'kings.chart_kings_title': '{className} 单科状元 vs 年级单科状元',
    'kings.chart_duel_title': '班级第一 vs 年级第一 对决',
    'kings.legend_class_top': '班级最高分',
    'kings.legend_grade_top': '年级最高分',
    'kings.legend_class_first': '班级第一 ({className})',
    'kings.legend_school_first': '校第一 (年级状元)',
    'params.reliability_title': '全卷信度 (α)',
    'params.reliability_desc': '基于克隆巴赫系数 (Cronbach\'s Alpha) 计算。值 > 0.7 表示测试具有较高的一致性。',
    'params.reliability_method': '计算方法：内部一致性信度',
    'params.reliability_stable': '测试稳定',
    'params.reliability_unstable': '信度较低',
    'params.matrix_title': '学科参数矩阵',
    'params.difficulty_discrimination': '难度与区分度矩阵',
    'params.total_participants': '参测总人数',
    'params.valid_records': '有效考试记录',
    'params.table_median': '中位数',
    'params.table_mode': '众数',
    'params.table_std_dev': '标准差 (σ)',
    'params.table_difficulty': '难度 (L)',
    'params.table_discrimination': '区分度 (D)',
    'params.table_max': '最高分',
    'params.table_mean': '均分',
    'subject.select_subject': '选择查看科目',
    'subject.select_classes': '选择查看班级',
    'subject.dist_title': '{subject} 在所选班级的分布情况 ({period})',
    'subject.focus_list': '关注名单：未达上线标准学生',
    'subject.focus_desc': '当前 {classes} 在 {subject} 科目共有 {count} 人未达标',
    'subject.no_below_line': '太棒了！所选群体在该科目中全员达标。',
    'subject.insight_title': '分析洞察',
    'subject.insight_desc': '当前图表展示了所选班级在 {subject} 科目的上线情况分布。排名计算基于 {period} 该科目的实际参考人数进行百分比适配。',
    'progress.period_select': '选择对比考试周期',
    'progress.period_x': '第一次考试 (x)',
    'progress.period_y': '第二次考试 (y)',
    'progress.class_filter': '按班级筛选',
    'progress.coefficient_formula': '进退步系数 (z) = 2 * (x - y) / (x + y)',
    'progress.table_name': '姓名',
    'progress.table_rank_x': '{period}级名',
    'progress.table_rank_change': '进退步名次',
    'progress.table_coefficient': '进退步系数',
    'progress.table_streak': '连续进退步',
    'progress.table_streak_up': '进 {count}',
    'progress.table_streak_down': '退 {count}',
    'progress.no_data': '当前筛选条件下无可用数据。',
    'progress.subtab_coefficient': '进退步系数 (点对点)',
    'progress.subtab_streak': '连续进退步 (区间趋势)',
    'student.search_placeholder': '搜索学生姓名...',
    'student.all_classes': '全部班级',
    'student.latest_rank': '最新名次',
    'student.academic_performer': '学业表现者',
    'student.avg_total': '历史平均总分',
    'student.improvement_total': '总分进步率',
    'student.trend_analysis': '趋势分析',
    'student.streak_msg': '连续{type} {count} 次',
    'student.streak_improvement': '进步',
    'student.streak_decline': '退步',
    'student.streak_stable': '稳定',
    'student.total_rank_change': '总位次变动',
    'student.rank_trend_title': '校排名趋势 (向上表示进步)',
    'student.score_vs_grade': '个人总分与年级均分对比',
    'student.radar_title': '学科竞争力雷达图',
    'student.radar_class': '班级平均',
    'student.radar_grade': '年级平均',
    'student.subject_trend_title': '{subject} 历史名次趋势',
    'student.ledger_title': '成绩总账单',
    'student.ledger_note': '注：学科背景色严格基于导入元数据推算的百分比阈值与该次考试实际参考人数动态匹配。',
    'student.ledger_period': '周期',
    'student.ledger_total': '总分',
    'student.ledger_class_rank': '班名',
    'student.ledger_grade_rank': '级名',
    'student.ledger_status': '上线情况',
    'student.select_hint': '请在上方选择一名学生以查看详细 analysis',
    'student.swot_title': '优劣势学科分析',
    'student.swot_desc': '基于选定考试 ({period}) 的总分位次对比单科位次',
    'student.swot_strengths': '优势学科',
    'student.swot_weaknesses': '弱势学科',
    'student.swot_stable': '发挥正常',
    'student.swot_empty': '暂无明显数据差异',
    'student.swot_calc_note': '注：单科排名位次优于总分位次5%以上判定为优势，低于5%以上判定为弱势。',
    'export.title': '数据导出与报告',
    'export.subtitle': '配置、预览并导出详细的成绩分析报告',
    'export.config_period': '选择考试周期',
    'export.config_classes': '班级范围',
    'export.options_title': '报告模块配置',
    'export.section_overview': '成绩概览 (Stats)',
    'export.section_charts': '可视化图表 (Charts)',
    'export.section_matrix': '班级对比矩阵 (Matrix)',
    'export.section_students': '优秀学生名单 (Top List)',
    'export.btn_print': '打印 / 保存 PDF',
    'export.btn_excel': '导出完整 Excel',
    'export.preview_header': '分析报告预览',
    'export.report_generated': '报告生成时间',
    'export.report_footer': '由 EduAnalytics 自动生成',
    'export.top_students_title': '优秀学生名单 (Top {count})',
    'export.student_limit_note': '注：因学生数量众多，打印报告仅展示所选班级的成绩详情表。',
    'export.module_config': '模块配置',
    'export.tab_overall': '整体数据报告',
    'export.tab_personal': '个人数据报告',
    'export.tab_tables': '完整表格报告',
    'export.select_student': '选择学生',
    'export.select_all_class': '全选班级学生',
    'export.table_raw_score': '原始成绩表',
    'export.table_ranks': '排名统计表',
    'export.table_stats': '班级统计表'
  },
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.manager': 'Data Manager',
    'nav.export': 'Export',
    'nav.source': 'Source',
    'hero.title': 'Unlock Deep Academic Insights',
    'hero.subtitle': 'Driven by Data',
    'hero.desc': 'Transform your raw student records into actionable pedagogical intelligence. Start by managing your exam data.',
    'hero.cta': 'Go to Data Manager',
    'stat.total_students': 'Total Students',
    'stat.classes': 'Classes',
    'stat.above_line': 'Above Line',
    'stat.best_score': 'Best Score',
    'tab.school': 'School View',
    'tab.comparison': 'Class Comparison',
    'tab.kings': 'Elite Benchmarks',
    'tab.parameters': 'Exam Parameters',
    'tab.subject': 'Subject Analysis',
    'tab.progress': 'Progress Analysis',
    'tab.student': 'Student Detail',
    'school.config_title': 'Admissions Thresholds Config',
    'school.imported_meta': 'Derived from Metadata',
    'school.rank_mode': 'By Absolute Rank',
    'school.percent_mode': 'By Percentage',
    'school.chart_admissions': 'Admissions Status',
    'school.chart_subjects': 'Subject Performance',
    'common.subject': 'Subject',
    'common.class': 'Class',
    'common.rank': 'Rank',
    'common.score': 'Score',
    'common.average': 'Average',
    'common.search': 'Search...',
    'common.select_all': 'Select All',
    'common.participants': 'Count',
    'wizard.step': 'Step',
    'wizard.upload': 'Upload',
    'wizard.config': 'Config',
    'wizard.mapping': 'Mapping',
    'wizard.drop_files': 'Drop your Excel files here',
    'wizard.supported_formats': 'Supported formats: .xlsx, .xls',
    'wizard.data_mode': 'Data Mode',
    'wizard.mode_complete': 'Whole School (Cohort)',
    'wizard.mode_complete_desc': 'Full ranking computation will be based on all available records.',
    'wizard.mode_partial': 'Partial Sample / Group',
    'wizard.mode_partial_desc': 'Only selected groups provided. Ranks might be skewed.',
    'wizard.table_layout': 'Table Layout',
    'wizard.layout_multi': 'One Exam Per File',
    'wizard.layout_multi_desc': 'Traditional format. Select multiple files to build a timeline.',
    'wizard.layout_single': 'Multi-Exam Summary Table',
    'wizard.layout_single_desc': 'Single file with grouped student records (e.g. 5 rows for 1 student).',
    'wizard.rank_source': 'Ranking Authority',
    'wizard.source_system': 'System Calculation',
    'wizard.source_system_desc': 'The system will derive rankings and admission status automatically from scores.',
    'wizard.source_import': 'Imported Metadata',
    'wizard.source_import_desc': 'Prioritize using pre-existing ranking and admission status columns.',
    'wizard.define_sequence': 'Define Exam Sequence (Comma separated)',
    'wizard.identity_cols': 'Identity Columns',
    'wizard.student_name': 'Student Name',
    'wizard.class_group': 'Class Group',
    'wizard.choose_col': '-- Choose Column --',
    'wizard.manual_input': '-- Manual Input --',
    'wizard.enter_class': 'Enter Class Name (e.g. 301)',
    'wizard.global_metrics': 'Global Metrics',
    'wizard.total_rank_col': 'Total Rank',
    'wizard.admission_status': 'Admission Status',
    'wizard.not_specified': '(Not Specified)',
    'wizard.subject_mapping': 'Subject Mapping',
    'wizard.selected_count': 'Selected',
    'wizard.mapping_hint': 'First specify Name and Class columns to reveal remaining fields.',
    'wizard.rank_col': 'Rank Col',
    'wizard.btn_discard': 'Discard & Close',
    'wizard.btn_back': 'Back',
    'wizard.btn_continue': 'Continue',
    'wizard.btn_confirm': 'Confirm & Build Dashboard',
    'wizard.processing': 'Processing Data...',
    'wizard.error_no_records': 'No student records found. Check mapping.',
    'manager.title': 'Exam Data Management',
    'manager.desc': 'Import, organize, and inspect your academic records.',
    'manager.btn_import': 'Import New Data',
    'manager.no_data_title': 'No Data Imported Yet',
    'manager.no_data_desc': 'Use the import wizard to upload Excel files and start analyzing student performance.',
    'manager.launch_wizard': 'Launch Import Wizard',
    'manager.manage_timeline': 'Manage Timeline',
    'manager.manage_timeline_desc': 'Reorder exams by dragging the handles. Select an exam to view detailed metadata and validation stats.',
    'manager.timeline_title': 'Exam Timeline',
    'manager.records': 'Records',
    'manager.full_dataset': 'Full Dataset',
    'manager.partial_dataset': 'Partial Dataset',
    'manager.delete_confirm': '⚠️ Warning: You are about to permanently delete all data related to "{name}". This includes scores and rankings for all students in this period. \n\nAre you sure you want to proceed?',
    'manager.details_title': 'Detailed Period Metadata',
    'manager.stats_participants': 'Participants',
    'manager.stats_avg': 'Avg. Score',
    'manager.stats_cohort_mean': 'Cohort Mean',
    'manager.stats_top_perf': 'Top Performance',
    'manager.stats_score': 'Score',
    'manager.stats_subject_coverage': 'Subject Coverage',
    'manager.stats_active_classes': 'Active Classes',
    'manager.btn_delete_exam': 'Delete this Exam',
    'manager.select_exam_hint_title': 'Select an exam',
    'manager.select_exam_hint_desc': 'Click on any exam in the timeline to view its specific metadata and analytics breakdown.',
    'comparison.title': 'Class Comparison Analysis',
    'comparison.desc': 'Comparing academic performance across selected groups.',
    'comparison.stat_highest_avg': 'Highest Average Score',
    'comparison.stat_points_avg': 'Points Average',
    'comparison.stat_most_top10': 'Most Top {threshold} Elite',
    'comparison.stat_students_top10': 'Students in Top {threshold}',
    'comparison.stat_strongest_bench': 'Strongest Bench (Top {threshold})',
    'comparison.stat_students_top50': 'Students in Top {threshold}',
    'comparison.title_matrix': 'Subject Competition Matrix',
    'comparison.matrix_desc': 'Highlighted cells indicate the leading class in that subject.',
    'comparison.matrix_header': 'Subject / Metric',
    'comparison.matrix_total_avg': 'TOTAL AVG',
    'comparison.matrix_subject_avg': 'Subject Specific Averages',
    'comparison.matrix_rank_dist': 'Ranking Distribution (Top Tier)',
    'comparison.count': 'Count',
    'comparison.chart_gap': 'Subject Performance Gap',
    'comparison.chart_density': 'Elite Density Heatmap',
    'comparison.chart_population_dist': 'Top Rank Distribution by Class',
    'comparison.ownership_title': 'Elite Ownership (Top {threshold})',
    'comparison.ownership_selector': 'Compare Threshold',
    'comparison.other_classes': 'Other Classes/Unassigned',
    'comparison.tier_others': 'Other Ranks',
    'kings.title': 'Elite Benchmarking',
    'kings.desc': 'Compare class leaders against grade-wide masters.',
    'kings.selector_prefix': 'Benchmark Class',
    'kings.chart_kings_title': '{className} Subject King vs Grade Subject King',
    'kings.chart_duel_title': 'First-in-Class vs First-in-Grade Duel',
    'kings.legend_class_top': 'Class Top',
    'kings.legend_grade_top': 'Grade Top',
    'kings.legend_class_first': '#1 in {className}',
    'kings.legend_school_first': '#1 in School (Grade King)',
    'params.reliability_title': 'Global Reliability (α)',
    'params.reliability_desc': 'Calculated using Cronbach\'s Alpha. A value > 0.7 indicates high internal consistency.',
    'params.reliability_method': 'Method: Internal Consistency',
    'params.reliability_stable': 'Test Stable',
    'params.reliability_unstable': 'Low Reliability',
    'params.matrix_title': 'Subject Parameter Matrix',
    'params.difficulty_discrimination': 'Difficulty & Discrimination Matrix',
    'params.total_participants': 'Total Participants',
    'params.valid_records': 'Valid Exam Records',
    'params.table_median': 'Median',
    'params.table_mode': 'Mode',
    'params.table_std_dev': 'Std Dev (σ)',
    'params.table_difficulty': 'Difficulty (L)',
    'params.table_discrimination': 'Discrimination (D)',
    'params.table_max': 'Max',
    'params.table_mean': 'Mean',
    'subject.select_subject': 'Select Subject',
    'subject.select_classes': 'Select Classes',
    'subject.dist_title': '{subject} Distribution in Selected Classes ({period})',
    'subject.focus_list': 'Focus List: Below Threshold',
    'subject.focus_desc': '{count} students below threshold in {subject} (Classes: {classes})',
    'subject.no_below_line': 'Great! All students in the selected group are above thresholds.',
    'subject.insight_title': 'Analysis Insight',
    'subject.insight_desc': 'This chart shows admission distribution for {subject}. Rankings are adapted based on actual participants in {period}.',
    'progress.period_select': 'Select Comparison Periods',
    'progress.period_x': 'First Exam (x)',
    'progress.period_y': 'Second Exam (y)',
    'progress.class_filter': 'Filter by Class',
    'progress.coefficient_formula': 'Coefficient (z) = 2 * (x - y) / (x + y)',
    'progress.table_name': 'Name',
    'progress.table_rank_x': 'Rank {period}',
    'progress.table_rank_change': 'Rank Change',
    'progress.table_coefficient': 'Coefficient',
    'progress.table_streak': 'Streak',
    'progress.table_streak_up': 'Up {count}',
    'progress.table_streak_down': 'Down {count}',
    'progress.no_data': 'No data available for the selected criteria.',
    'progress.subtab_coefficient': 'Coefficient (2-Point)',
    'progress.subtab_streak': 'Streak (Range Trend)',
    'student.search_placeholder': 'Search student name...',
    'student.all_classes': 'All Classes',
    'student.latest_rank': 'Latest Rank',
    'student.academic_performer': 'Academic Performer',
    'student.avg_total': 'Average Total Score',
    'student.improvement_total': 'Total Score Imp.',
    'student.trend_analysis': 'Trend Analysis',
    'student.streak_msg': 'Consecutive {type} {count} times',
    'student.streak_improvement': 'Improvement',
    'student.streak_decline': 'Decline',
    'student.streak_stable': 'Stable',
    'student.total_rank_change': 'Total Rank Change',
    'student.rank_trend_title': 'School Ranking Trend (Higher is Better)',
    'student.score_vs_grade': 'Total Score vs Grade Average',
    'student.radar_title': 'Subject Competency Radar',
    'student.radar_class': 'Class Avg',
    'student.radar_grade': 'Grade Avg',
    'student.subject_trend_title': '{subject} Historical Rank Trend',
    'student.ledger_title': 'Score Ledger',
    'student.ledger_note': 'Note: Cell colors are dynamically matched based on metadata percentiles and actual participants.',
    'student.ledger_period': 'Period',
    'student.ledger_total': 'Total',
    'student.ledger_class_rank': 'Class Rank',
    'student.ledger_grade_rank': 'Grade Rank',
    'student.ledger_status': 'Status',
    'student.select_hint': 'Please select a student above to view detailed analysis',
    'student.swot_title': 'Subject Strengths & Weaknesses',
    'student.swot_desc': 'Comparing subject percentiles against total score percentile for {period}',
    'student.swot_strengths': 'Strengths',
    'student.swot_weaknesses': 'Weaknesses',
    'student.swot_stable': 'Balanced',
    'student.swot_empty': 'No significant deviations found',
    'student.swot_calc_note': 'Note: Strengths are subjects performing 5%+ better than the overall percentile; Weaknesses are 5%+ worse.',
    'export.title': 'Data Export & Reports',
    'export.subtitle': 'Configure, preview and export detailed analysis reports',
    'export.config_period': 'Select Exam Period',
    'export.config_classes': 'Class Range',
    'export.options_title': 'Report Modules Configuration',
    'export.section_overview': 'Score Overview (Stats)',
    'export.section_charts': 'Visual Charts (Charts)',
    'export.section_matrix': 'Class Comparison Matrix',
    'export.section_students': 'Top Student List',
    'export.btn_print': 'Print / Save PDF',
    'export.btn_excel': 'Export Full Excel',
    'export.preview_header': 'Analysis Report Preview',
    'export.report_generated': 'Generated on',
    'export.report_footer': 'Automatically generated by EduAnalytics',
    'export.top_students_title': 'Top Student List (Top {count})',
    'export.student_limit_note': 'Note: Due to high volume, report prints details for the selected class only.',
    'export.module_config': 'Module Config',
    'export.tab_overall': 'Overall Report',
    'export.tab_personal': 'Individual Report',
    'export.tab_tables': 'Full Table Report',
    'export.select_student': 'Select Student',
    'export.select_all_class': 'Select All Students in Class',
    'export.table_raw_score': 'Raw Score Table',
    'export.table_ranks': 'Rank Statistics Table',
    'export.table_stats': 'Class Statistics Table'
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem('edu_lang') as Language) || 'zh';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('edu_lang', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useTranslation must be used within LanguageProvider');
  return context;
};
